preset: psr2

risky: false

enabled:
  - elseif
  - new_with_braces

disabled:
  - braces
  - cast_spaces

finder:
  exclude:
    - "tests"
    - "templates"
    - "translations"
  name:
    - "*.php"
