preset: psr2

risky: false

php:
  braces:
    - allow_single_line_closure: false
    - position_after_functions_and_oop_constructs: "next"

finder:
  exclude:
    - "tests"
    - "templates"
    - "translations"
  name:
    - "*.php"
